// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnnlepxzjrmlvpfawzem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubmxlcHh6anJtbHZwZmF3emVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MzI5NTUsImV4cCI6MjA2ODIwODk1NX0.bwYG2pTxJMaXvOm-PJusWeFBAbnCNa35R8_zT9dpZak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});